title: "Okafor Chisom | Cybersecurity & DevSecOps Portfolio"
description: "Portfolio showcasing cybersecurity, cloud, DevSecOps, and Python automation projects"
baseurl: ""
url: ""

theme: minima

minima:
  skin: dark
